#!/bin/bash

# ----
# Resolve issues with IP aliasing for Amazon EC2 linux virtual machines
# ----
#


if [ $# -lt 1 ]
then
        echo "No command specified"  
	echo "Usage: $0 start, $0 stop, $0 restart or $0 print"
	echo "Execute $0 -h or $0 help for more detailed usage information"
        exit
fi

function mac-grab {
	MAC_ADDR=$(ifconfig eth0 | sed -n 's/.*ether \([a-f0-9:]*\).*/\1/p')
}

function public-grab {
	PUBLIC=($(curl -s -f http://169.254.169.254/latest/meta-data/public-ipv4))
}

function private-grab {
	PRIVATE=($(curl -s -f http://169.254.169.254/latest/meta-data/network/interfaces/macs/$MAC_ADDR/local-ipv4s))
}

function private-loop {
	for priv in ${PRIVATE[@]:1};
        do
                echo "Adding IP: $priv"
                ip addr add dev eth0 $priv/20
        done
}

case "$1" in

'-h') printf "\nAliaser v0.01\nUsage: $0 -h\n$0 help\n$0 version\n$0 start\n$0 restart\n$0 stop\n$0 print\n\n"
	;;

'version') printf "aliaser v0.01
-----------------------------------
©2015 Josh Wieder\nhttp://www.joshwieder.net/\njosh.wieder@live.com
-----------------------------------
aliaser comes with ABSOLUTELY NO WARRANTY.
This is free software made available through
the GNU General Public License v2. You are
welcome to redistribute it under certain
conditions - see LICENSE for details.\n\n"
        ;;

'start') mac-grab
	private-grab
	private-loop
	;;

'restart') mac-grab
	private-grab        
	private-loop
	;;

'stop') service network restart
	;;

print) mac-grab
	private-grab
        for priv in ${PRIVATE[@]:1};
        do 
		printf "Your assigned secondary private IP addresses are:  %s\n" "$priv"
        done
        
	public-grab
        printf "Your assigned secondary public IP addresses are:  %s\n" "$PUBLIC";
        ;;

*) echo "Invalid option"
	;;
esac
